apiVersion: v1
kind: Pod
metadata:
  name: mock-gpu-consumer
spec:
  restartPolicy: Never
  containers:
    - name: app
      image: busybox:1.36
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          echo "NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}";
          echo "MOCK_NVIDIA_VISIBLE_DEVICES=${MOCK_NVIDIA_VISIBLE_DEVICES}";
          sleep 30
      resources:
        limits:
          nvidia.com/gpu: 1
